// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20260903193544_repararlocalidad")]
    partial class repararlocalidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.Models.Cliente", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Address = "Calle AURA",
                            Created_at = new DateTimeOffset(new DateTime(2026, 9, 3, 16, 35, 42, 193, DateTimeKind.Unspecified).AddTicks(6604), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "67676767676767",
                            Firstname = "Enzo",
                            IsDeleted = false,
                            Lastname = "Cabrera",
                            LocalidadId = 1
                        },
                        new
                        {
                            id = 2,
                            Address = "Avenida Siempre Viva 456",
                            Created_at = new DateTimeOffset(new DateTime(2026, 9, 3, 16, 35, 42, 193, DateTimeKind.Unspecified).AddTicks(6668), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "87654321",
                            Firstname = "María",
                            IsDeleted = false,
                            Lastname = "González",
                            LocalidadId = 2
                        },
                        new
                        {
                            id = 3,
                            Address = "Callejón del Beso 789",
                            Created_at = new DateTimeOffset(new DateTime(2026, 9, 3, 16, 35, 42, 193, DateTimeKind.Unspecified).AddTicks(6672), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "11223344",
                            Firstname = "Pedro",
                            IsDeleted = false,
                            Lastname = "López",
                            LocalidadId = 3
                        });
                });

            modelBuilder.Entity("Services.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "San Justo"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Santa Fe"
                        });
                });

            modelBuilder.Entity("Services.Models.Cliente", b =>
                {
                    b.HasOne("Services.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });
#pragma warning restore 612, 618
        }
    }
}
